services:
  - type: web
    name: fitness-app
    env: static
    buildCommand: |
      npm install
      npm run build
      echo "Checking for publish directories:"
      ls -la
      echo "---"
      ls -la public || echo "No public dir"
      echo "---"
      ls -la dist || echo "No dist dir"
      echo "---"
      ls -la public/dist || echo "No public/dist dir"
    staticPublishPath: public
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 