services:
  - type: web
    name: fitness-app
    env: static
    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=1024"
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 