services:
  - type: web
    name: fitness-app
    env: static
    buildCommand: |
      npm install
      mkdir -p dist
      npm run build
      ls -la dist
      ls -la
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 