services:
  - type: web
    name: fitness-app
    env: static
    buildCommand: |
      npm install -g npm@10.2.3
      npm install -g create-react-app
      npm install
      npx react-scripts build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: PATH
        value: /opt/render/project/node_modules/.bin:$PATH
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 