services:
  - type: web
    name: fitness-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production 