services:
  - type: web
    name: fitness-app
    env: static
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: SKIP_PREFLIGHT_CHECK
        value: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 